# Generated by Django 5.0.6 on 2024-07-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crude', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_iamge',
            field=models.ImageField(default='default.jpg', upload_to='std_image'),
        ),
        migrations.AlterField(
            model_name='students',
            name='marks',
            field=models.IntegerField(default=100),
        ),
    ]
