# Generated by Django 5.0.6 on 2024-07-03 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crude', '0002_students_student_iamge_alter_students_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='student_iamge',
            new_name='student_image',
        ),
    ]
